FROM azabost/android-sdk:base-jdk17

# To get a full list of available options you can use:
#  sdkmanager --list --verbose

RUN sdkmanager 'platform-tools'
RUN sdkmanager 'platforms;android-34'
RUN sdkmanager 'build-tools;34.0.0'
RUN sdkmanager 'extras;google;google_play_services'
